-- MySQL Script generated by MySQL Workbench
-- Sun Oct  5 11:23:17 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  `endereco` VARCHAR(45) NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Veiculo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Veiculo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Veiculo` (
  `idVeiculo` INT NOT NULL,
  `placa` VARCHAR(45) NULL,
  `modelo` VARCHAR(45) NULL,
  `ano` VARCHAR(45) NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idVeiculo`, `Cliente_idCliente`),
  INDEX `fk_Veiculo_Cliente_idx` (`Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Veiculo_Cliente`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ordem_Servico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Ordem_Servico` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Ordem_Servico` (
  `idOrdem_Servico` INT NOT NULL,
  `data_emissao` DATE NULL,
  `data_conclusao` DATE NULL,
  `status` VARCHAR(45) NULL,
  `valor_total` FLOAT NULL,
  `Veiculo_idVeiculo` INT NOT NULL,
  PRIMARY KEY (`idOrdem_Servico`, `Veiculo_idVeiculo`),
  INDEX `fk_Ordem_Servico_Veiculo1_idx` (`Veiculo_idVeiculo` ASC) VISIBLE,
  CONSTRAINT `fk_Ordem_Servico_Veiculo1`
    FOREIGN KEY (`Veiculo_idVeiculo`)
    REFERENCES `mydb`.`Veiculo` (`idVeiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mecanico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Mecanico` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Mecanico` (
  `idMecanico` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `codigo` VARCHAR(45) NULL,
  `endereco` VARCHAR(45) NULL,
  `especialidade` VARCHAR(45) NULL,
  PRIMARY KEY (`idMecanico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Equipe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Equipe` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Equipe` (
  `idEquipe` INT NOT NULL,
  `nome_equipe` VARCHAR(45) NULL,
  PRIMARY KEY (`idEquipe`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Equipe_has_Mecanico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Equipe_has_Mecanico` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Equipe_has_Mecanico` (
  `Equipe_idEquipe` INT NOT NULL,
  `Mecanico_idMecanico` INT NOT NULL,
  PRIMARY KEY (`Equipe_idEquipe`, `Mecanico_idMecanico`),
  INDEX `fk_Equipe_has_Mecanico_Mecanico1_idx` (`Mecanico_idMecanico` ASC) VISIBLE,
  INDEX `fk_Equipe_has_Mecanico_Equipe1_idx` (`Equipe_idEquipe` ASC) VISIBLE,
  CONSTRAINT `fk_Equipe_has_Mecanico_Equipe1`
    FOREIGN KEY (`Equipe_idEquipe`)
    REFERENCES `mydb`.`Equipe` (`idEquipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Equipe_has_Mecanico_Mecanico1`
    FOREIGN KEY (`Mecanico_idMecanico`)
    REFERENCES `mydb`.`Mecanico` (`idMecanico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Servico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Servico` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Servico` (
  `idServico` INT NOT NULL,
  `descricao` VARCHAR(45) NULL,
  `valor_ref` FLOAT NULL,
  PRIMARY KEY (`idServico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Peça`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Peça` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Peça` (
  `idPeça` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `valor` FLOAT NULL,
  PRIMARY KEY (`idPeça`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ordem_Servico_has_Servico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Ordem_Servico_has_Servico` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Ordem_Servico_has_Servico` (
  `Ordem_Servico_idOrdem_Servico` INT NOT NULL,
  `Ordem_Servico_Veiculo_idVeiculo` INT NOT NULL,
  `Servico_idServico` INT NOT NULL,
  `quantidade` FLOAT NULL,
  `valor_total` FLOAT NULL,
  PRIMARY KEY (`Ordem_Servico_idOrdem_Servico`, `Ordem_Servico_Veiculo_idVeiculo`, `Servico_idServico`),
  INDEX `fk_Ordem_Servico_has_Servico_Servico1_idx` (`Servico_idServico` ASC) VISIBLE,
  INDEX `fk_Ordem_Servico_has_Servico_Ordem_Servico1_idx` (`Ordem_Servico_idOrdem_Servico` ASC, `Ordem_Servico_Veiculo_idVeiculo` ASC) VISIBLE,
  CONSTRAINT `fk_Ordem_Servico_has_Servico_Ordem_Servico1`
    FOREIGN KEY (`Ordem_Servico_idOrdem_Servico` , `Ordem_Servico_Veiculo_idVeiculo`)
    REFERENCES `mydb`.`Ordem_Servico` (`idOrdem_Servico` , `Veiculo_idVeiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ordem_Servico_has_Servico_Servico1`
    FOREIGN KEY (`Servico_idServico`)
    REFERENCES `mydb`.`Servico` (`idServico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Equipe_has_Ordem_Servico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Equipe_has_Ordem_Servico` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Equipe_has_Ordem_Servico` (
  `Equipe_idEquipe` INT NOT NULL,
  `Ordem_Servico_idOrdem_Servico` INT NOT NULL,
  PRIMARY KEY (`Equipe_idEquipe`, `Ordem_Servico_idOrdem_Servico`),
  INDEX `fk_Equipe_has_Ordem_Servico_Ordem_Servico1_idx` (`Ordem_Servico_idOrdem_Servico` ASC) VISIBLE,
  INDEX `fk_Equipe_has_Ordem_Servico_Equipe1_idx` (`Equipe_idEquipe` ASC) VISIBLE,
  CONSTRAINT `fk_Equipe_has_Ordem_Servico_Equipe1`
    FOREIGN KEY (`Equipe_idEquipe`)
    REFERENCES `mydb`.`Equipe` (`idEquipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Equipe_has_Ordem_Servico_Ordem_Servico1`
    FOREIGN KEY (`Ordem_Servico_idOrdem_Servico`)
    REFERENCES `mydb`.`Ordem_Servico` (`idOrdem_Servico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ordem_Servico_has_Peça`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Ordem_Servico_has_Peça` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Ordem_Servico_has_Peça` (
  `Ordem_Servico_idOrdem_Servico` INT NOT NULL,
  `Ordem_Servico_Veiculo_idVeiculo` INT NOT NULL,
  `Peça_idPeça` INT NOT NULL,
  `quantidade` FLOAT NULL,
  `valor_total` FLOAT NULL,
  PRIMARY KEY (`Ordem_Servico_idOrdem_Servico`, `Ordem_Servico_Veiculo_idVeiculo`, `Peça_idPeça`),
  INDEX `fk_Ordem_Servico_has_Peça_Peça1_idx` (`Peça_idPeça` ASC) VISIBLE,
  INDEX `fk_Ordem_Servico_has_Peça_Ordem_Servico1_idx` (`Ordem_Servico_idOrdem_Servico` ASC, `Ordem_Servico_Veiculo_idVeiculo` ASC) VISIBLE,
  CONSTRAINT `fk_Ordem_Servico_has_Peça_Ordem_Servico1`
    FOREIGN KEY (`Ordem_Servico_idOrdem_Servico` , `Ordem_Servico_Veiculo_idVeiculo`)
    REFERENCES `mydb`.`Ordem_Servico` (`idOrdem_Servico` , `Veiculo_idVeiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ordem_Servico_has_Peça_Peça1`
    FOREIGN KEY (`Peça_idPeça`)
    REFERENCES `mydb`.`Peça` (`idPeça`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
